/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calc;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;


/**
 *
 * @author Mostafa Mahmoud
 */
public class MainFrame extends javax.swing.JFrame {

    // my vairiables-
    private JButton btw[];
    private JButton Operations[];
    
    /**
     * Creates new form NewJFrame
     */
    public MainFrame() {
        initComponents();
        Color col = new Color(39,49,57);
        getContentPane().setBackground(col);
        
      //buttons in main 
        btw = new JButton[25];
        btw[0] = zero;
        btw[1] = one;
        btw[2] = two;
        btw[3] = three;
        btw[4] = four;
        btw[5] = five;
        btw[6] = six;
        btw[7] = seven;
        btw[8] = eight;
        btw[9] = nine;
        btw[10] = DEL;
        btw[11] = mult;
        btw[12] = divid;
        btw[13] = plus;
        btw[14] = minus;
        btw[15] =AC;
        btw[16] =equal;
        btw[17] =tan;
        btw[18] =ANS;
        btw[19] =dot;
        btw[20] =jButton13;
        btw[21] =jButton21;
        btw[22] =jButton22;
        btw[23] =jButton23;
        btw[24] =tan;
    }
    //my functions-
    
    private void numberOnly(java.awt.event.KeyEvent evt){
               char c =evt.getKeyChar();
        if(!Character.isDigit(c)&&c!='.'){
            evt.consume();
        }
    }
    private void handleAreaCalculation(String shapeType, String dimensionText1, String dimensionText2, JLabel lawTxt, JLabel resultTxt) {
        try {
            double dimension1 = Double.parseDouble(dimensionText1);
            double dimension2 = 0.0;
            if (!dimensionText2.isEmpty()) {
                   dimension2 = Double.parseDouble(dimensionText2);
                } else {
                    dimension2 = 0;
                }

            double result = 0;
            Shape s;
            switch (shapeType.toLowerCase()) {
                case "square":
                    s = new Square(dimension1);
                    break;
                case "rectangle":
                    s = new Rectangle(dimension1,dimension2);
                    break;
                default:
                    throw new Exception();
            }
                result = s.calculateArea();
                resultTxt.setText(String.valueOf(result));
                lawTxt.setText(s.getLaw());

        } catch (Exception e) {
            showMessageDialog(null, "ERROR\nINVALID INPUT", "INVALID INPUT", ERROR_MESSAGE);
        }
    }
    private void set(String s){
        String all = txt.getText()+s;
        txt.setText(all);
    }
    private void setBtwColor(Color color) {
        for(JButton b:btw){
            b.setBackground(color);
        }
}
    private void setBtwTxtColor(Color color){
        for(JButton b:btw){
            b.setForeground(color);
        }
    }
    //---------------------------------------------------
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        BasicWin = new javax.swing.JPanel();
        txt = new javax.swing.JTextField();
        dot = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        one = new javax.swing.JButton();
        two = new javax.swing.JButton();
        three = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        DEL = new javax.swing.JButton();
        mult = new javax.swing.JButton();
        divid = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        AC = new javax.swing.JButton();
        equal = new javax.swing.JButton();
        tan = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        ANS = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        ModeWin = new javax.swing.JPanel();
        AreasWin = new javax.swing.JPanel();
        square = new javax.swing.JButton();
        rectangular = new javax.swing.JButton();
        triangle = new javax.swing.JButton();
        rhombus = new javax.swing.JButton();
        polygon = new javax.swing.JButton();
        squareWin = new javax.swing.JPanel();
        txt_sideLength = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        squareAreaResult = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        SqAreaLaw = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        rectangularWin = new javax.swing.JPanel();
        txtLength = new javax.swing.JTextField();
        txtWidth = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        RecAreaResult = new javax.swing.JLabel();
        RecAreaLaw = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.orange);
        setResizable(false);

        BasicWin.setBackground(new java.awt.Color(32, 39, 44));

        txt.setBackground(new java.awt.Color(32, 39, 44));
        txt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txt.setForeground(new java.awt.Color(255, 255, 255));
        txt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt.setName("txt"); // NOI18N
        txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActionPerformed(evt);
            }
        });

        dot.setBackground(new java.awt.Color(54, 67, 76));
        dot.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        dot.setForeground(new java.awt.Color(226, 241, 231));
        dot.setText(".");
        dot.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotActionPerformed(evt);
            }
        });

        zero.setBackground(new java.awt.Color(54, 67, 76));
        zero.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        zero.setForeground(new java.awt.Color(226, 241, 231));
        zero.setText("0");
        zero.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        zero.setName("zero"); // NOI18N
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });

        one.setBackground(new java.awt.Color(54, 67, 76));
        one.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        one.setForeground(new java.awt.Color(226, 241, 231));
        one.setText("1");
        one.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });

        two.setBackground(new java.awt.Color(54, 67, 76));
        two.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        two.setForeground(new java.awt.Color(226, 241, 231));
        two.setText("2");
        two.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });

        three.setBackground(new java.awt.Color(54, 67, 76));
        three.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        three.setForeground(new java.awt.Color(226, 241, 231));
        three.setText("3");
        three.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });

        four.setBackground(new java.awt.Color(54, 67, 76));
        four.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        four.setForeground(new java.awt.Color(226, 241, 231));
        four.setText("4");
        four.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });

        five.setBackground(new java.awt.Color(54, 67, 76));
        five.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        five.setForeground(new java.awt.Color(226, 241, 231));
        five.setText("5");
        five.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });

        six.setBackground(new java.awt.Color(54, 67, 76));
        six.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        six.setForeground(new java.awt.Color(226, 241, 231));
        six.setText("6");
        six.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });

        seven.setBackground(new java.awt.Color(54, 67, 76));
        seven.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        seven.setForeground(new java.awt.Color(226, 241, 231));
        seven.setText("7");
        seven.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });

        eight.setBackground(new java.awt.Color(54, 67, 76));
        eight.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        eight.setForeground(new java.awt.Color(226, 241, 231));
        eight.setText("8");
        eight.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });

        nine.setBackground(new java.awt.Color(54, 67, 76));
        nine.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nine.setForeground(new java.awt.Color(226, 241, 231));
        nine.setText("9");
        nine.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });

        DEL.setBackground(new java.awt.Color(54, 67, 76));
        DEL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DEL.setForeground(new java.awt.Color(226, 241, 231));
        DEL.setText("DEL");
        DEL.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        DEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELActionPerformed(evt);
            }
        });

        mult.setBackground(new java.awt.Color(54, 67, 76));
        mult.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mult.setForeground(new java.awt.Color(226, 241, 231));
        mult.setText("x");
        mult.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multActionPerformed(evt);
            }
        });

        divid.setBackground(new java.awt.Color(54, 67, 76));
        divid.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        divid.setForeground(new java.awt.Color(226, 241, 231));
        divid.setText("÷");
        divid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        divid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividActionPerformed(evt);
            }
        });

        plus.setBackground(new java.awt.Color(54, 67, 76));
        plus.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        plus.setForeground(new java.awt.Color(226, 241, 231));
        plus.setText("+");
        plus.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });

        minus.setBackground(new java.awt.Color(54, 67, 76));
        minus.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        minus.setForeground(new java.awt.Color(226, 241, 231));
        minus.setText("-");
        minus.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });

        AC.setBackground(new java.awt.Color(54, 67, 76));
        AC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AC.setForeground(new java.awt.Color(226, 241, 231));
        AC.setText("AC");
        AC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        AC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACActionPerformed(evt);
            }
        });

        equal.setBackground(new java.awt.Color(54, 67, 76));
        equal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        equal.setForeground(new java.awt.Color(226, 241, 231));
        equal.setText("=");
        equal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });

        tan.setBackground(new java.awt.Color(54, 67, 76));
        tan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tan.setForeground(new java.awt.Color(226, 241, 231));
        tan.setText("tan");
        tan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(54, 67, 76));
        jButton13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton13.setForeground(new java.awt.Color(226, 241, 231));
        jButton13.setText("(");
        jButton13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton21.setBackground(new java.awt.Color(54, 67, 76));
        jButton21.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton21.setForeground(new java.awt.Color(226, 241, 231));
        jButton21.setText(")");
        jButton21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton22.setBackground(new java.awt.Color(54, 67, 76));
        jButton22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton22.setForeground(new java.awt.Color(226, 241, 231));
        jButton22.setText("sin");
        jButton22.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton23.setBackground(new java.awt.Color(54, 67, 76));
        jButton23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton23.setForeground(new java.awt.Color(226, 241, 231));
        jButton23.setText("cos");
        jButton23.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        ANS.setBackground(new java.awt.Color(54, 67, 76));
        ANS.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ANS.setForeground(new java.awt.Color(226, 241, 231));
        ANS.setText("ANS");
        ANS.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ANS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANSActionPerformed(evt);
            }
        });

        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jToggleButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jToggleButton1KeyPressed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DARKMODE ON");

        javax.swing.GroupLayout BasicWinLayout = new javax.swing.GroupLayout(BasicWin);
        BasicWin.setLayout(BasicWinLayout);
        BasicWinLayout.setHorizontalGroup(
            BasicWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
            .addGroup(BasicWinLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(BasicWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BasicWinLayout.createSequentialGroup()
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(BasicWinLayout.createSequentialGroup()
                        .addGroup(BasicWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BasicWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BasicWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dot, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BasicWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BasicWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ANS, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BasicWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(equal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BasicWinLayout.createSequentialGroup()
                        .addGroup(BasicWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DEL, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mult, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BasicWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tan, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BasicWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AC, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(divid, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BasicWinLayout.setVerticalGroup(
            BasicWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BasicWinLayout.createSequentialGroup()
                .addComponent(txt, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BasicWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BasicWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BasicWinLayout.createSequentialGroup()
                        .addGroup(BasicWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(BasicWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BasicWinLayout.createSequentialGroup()
                                .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BasicWinLayout.createSequentialGroup()
                                .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dot, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BasicWinLayout.createSequentialGroup()
                        .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ANS, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BasicWinLayout.createSequentialGroup()
                        .addGroup(BasicWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(BasicWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BasicWinLayout.createSequentialGroup()
                                .addComponent(DEL, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(mult, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BasicWinLayout.createSequentialGroup()
                                .addComponent(AC, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(divid, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(equal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );

        dot.getAccessibleContext().setAccessibleDescription("");
        zero.getAccessibleContext().setAccessibleDescription("");
        one.getAccessibleContext().setAccessibleDescription("");
        two.getAccessibleContext().setAccessibleDescription("");
        three.getAccessibleContext().setAccessibleDescription("");
        four.getAccessibleContext().setAccessibleDescription("");
        five.getAccessibleContext().setAccessibleDescription("");
        six.getAccessibleContext().setAccessibleDescription("");
        seven.getAccessibleContext().setAccessibleDescription("");
        eight.getAccessibleContext().setAccessibleDescription("");
        nine.getAccessibleContext().setAccessibleDescription("");
        DEL.getAccessibleContext().setAccessibleDescription("");
        mult.getAccessibleContext().setAccessibleDescription("");
        divid.getAccessibleContext().setAccessibleDescription("");
        plus.getAccessibleContext().setAccessibleDescription("");
        minus.getAccessibleContext().setAccessibleDescription("");
        AC.getAccessibleContext().setAccessibleDescription("");
        equal.getAccessibleContext().setAccessibleDescription("");
        tan.getAccessibleContext().setAccessibleDescription("");
        jButton13.getAccessibleContext().setAccessibleDescription("");
        jButton21.getAccessibleContext().setAccessibleDescription("");
        jButton22.getAccessibleContext().setAccessibleDescription("");
        jButton23.getAccessibleContext().setAccessibleDescription("");
        ANS.getAccessibleContext().setAccessibleDescription("");

        jTabbedPane1.addTab("main", BasicWin);

        javax.swing.GroupLayout ModeWinLayout = new javax.swing.GroupLayout(ModeWin);
        ModeWin.setLayout(ModeWinLayout);
        ModeWinLayout.setHorizontalGroup(
            ModeWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );
        ModeWinLayout.setVerticalGroup(
            ModeWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("MODE", ModeWin);

        square.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        square.setText("square");
        square.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareActionPerformed(evt);
            }
        });

        rectangular.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rectangular.setText("rectangular");
        rectangular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rectangularActionPerformed(evt);
            }
        });

        triangle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        triangle.setText("triangle");
        triangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                triangleActionPerformed(evt);
            }
        });

        rhombus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rhombus.setText("rhombus");
        rhombus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rhombusActionPerformed(evt);
            }
        });

        polygon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        polygon.setText("rhombus");
        polygon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                polygonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AreasWinLayout = new javax.swing.GroupLayout(AreasWin);
        AreasWin.setLayout(AreasWinLayout);
        AreasWinLayout.setHorizontalGroup(
            AreasWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AreasWinLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(AreasWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(triangle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(polygon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rectangular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(square, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rhombus, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(312, Short.MAX_VALUE))
        );
        AreasWinLayout.setVerticalGroup(
            AreasWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AreasWinLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(square, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rectangular, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(triangle, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rhombus, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(polygon, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("area caluc", AreasWin);

        squareWin.setBackground(new java.awt.Color(32, 39, 44));

        txt_sideLength.setBackground(new java.awt.Color(32, 39, 44));
        txt_sideLength.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txt_sideLength.setForeground(new java.awt.Color(226, 241, 231));
        txt_sideLength.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(226, 241, 231)));
        txt_sideLength.setCaretColor(new java.awt.Color(32, 39, 44));
        txt_sideLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sideLengthActionPerformed(evt);
            }
        });
        txt_sideLength.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_sideLengthKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(226, 241, 231));
        jLabel2.setText("Length (L) meter");

        squareAreaResult.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        squareAreaResult.setForeground(new java.awt.Color(226, 241, 231));
        squareAreaResult.setToolTipText("");

        jButton1.setBackground(new java.awt.Color(89, 89, 89));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(226, 241, 231));
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        SqAreaLaw.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        SqAreaLaw.setForeground(new java.awt.Color(226, 241, 231));

        jButton2.setBackground(new java.awt.Color(54, 67, 76));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(226, 241, 231));
        jButton2.setText("Calculate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout squareWinLayout = new javax.swing.GroupLayout(squareWin);
        squareWin.setLayout(squareWinLayout);
        squareWinLayout.setHorizontalGroup(
            squareWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(squareWinLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(squareWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(SqAreaLaw)
                    .addComponent(jLabel2)
                    .addGroup(squareWinLayout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(txt_sideLength)
                    .addComponent(squareAreaResult))
                .addGap(69, 69, 69))
        );
        squareWinLayout.setVerticalGroup(
            squareWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(squareWinLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txt_sideLength, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(squareWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(SqAreaLaw)
                .addGap(30, 30, 30)
                .addComponent(squareAreaResult)
                .addGap(69, 69, 69))
        );

        jTabbedPane1.addTab("square", squareWin);

        rectangularWin.setBackground(new java.awt.Color(32, 39, 44));

        txtLength.setBackground(new java.awt.Color(32, 39, 44));
        txtLength.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtLength.setForeground(new java.awt.Color(226, 241, 231));
        txtLength.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(226, 241, 231)));
        txtLength.setCaretColor(new java.awt.Color(32, 39, 44));
        txtLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLengthActionPerformed(evt);
            }
        });
        txtLength.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLengthKeyTyped(evt);
            }
        });

        txtWidth.setBackground(new java.awt.Color(32, 39, 44));
        txtWidth.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtWidth.setForeground(new java.awt.Color(226, 241, 231));
        txtWidth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(226, 241, 231)));
        txtWidth.setCaretColor(new java.awt.Color(32, 39, 44));
        txtWidth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWidthActionPerformed(evt);
            }
        });
        txtWidth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtWidthKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(226, 241, 231));
        jLabel3.setText("Width (w)");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(226, 241, 231));
        jLabel4.setText("Length (L)");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(226, 241, 231));
        jLabel5.setText("meter");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(226, 241, 231));
        jLabel6.setText("meter");

        jButton3.setBackground(new java.awt.Color(89, 89, 89));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(226, 241, 231));
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(54, 67, 76));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(226, 241, 231));
        jButton4.setText("Calculate");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        RecAreaResult.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        RecAreaResult.setForeground(new java.awt.Color(226, 241, 231));
        RecAreaResult.setToolTipText("");

        RecAreaLaw.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        RecAreaLaw.setForeground(new java.awt.Color(226, 241, 231));

        javax.swing.GroupLayout rectangularWinLayout = new javax.swing.GroupLayout(rectangularWin);
        rectangularWin.setLayout(rectangularWinLayout);
        rectangularWinLayout.setHorizontalGroup(
            rectangularWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rectangularWinLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(rectangularWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(RecAreaResult)
                    .addComponent(RecAreaLaw)
                    .addGroup(rectangularWinLayout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, rectangularWinLayout.createSequentialGroup()
                        .addGroup(rectangularWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(8, 8, 8)
                        .addGroup(rectangularWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, rectangularWinLayout.createSequentialGroup()
                                .addComponent(txtLength, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, rectangularWinLayout.createSequentialGroup()
                                .addComponent(txtWidth)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)))))
                .addGap(85, 85, 85))
        );
        rectangularWinLayout.setVerticalGroup(
            rectangularWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rectangularWinLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(rectangularWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLength, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(12, 12, 12)
                .addGroup(rectangularWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(txtWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(rectangularWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(RecAreaLaw)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RecAreaResult)
                .addGap(75, 75, 75))
        );

        jTabbedPane1.addTab("rectangular", rectangularWin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("main paga");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void polygonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_polygonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_polygonActionPerformed

    private void rhombusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rhombusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rhombusActionPerformed

    private void triangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_triangleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_triangleActionPerformed

    private void rectangularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectangularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rectangularActionPerformed

    private void squareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_squareActionPerformed

         //area caluc Panel
    private void jToggleButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jToggleButton1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1KeyPressed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (jToggleButton1.isSelected()) {//لو كان شغال هيشغل اليت مود

            jLabel1.setText("DARKMODE OFF");
            Color color_white = new Color(255, 255, 255);
            Color color_txt_light = new Color(207,209,208);
            Color color_label_dark = new Color(0,0,0);
            getContentPane().setBackground(color_white);
            txt.setBackground(color_txt_light );
            txt.setForeground(color_label_dark);
            jLabel1.setForeground(color_label_dark);
            setBtwColor(color_txt_light);
            setBtwTxtColor(color_label_dark);
            BasicWin.setBackground(color_txt_light);

        } else {

            jLabel1.setText("DARKMODE ON");
            Color color_dark = new Color(39,49,57);
            Color color_white = new Color(255, 255, 255);

            Color colot_btw_dark = new Color(54,67,76);
            getContentPane().setBackground(color_dark);
            jLabel1.setForeground(color_white);
            BasicWin.setBackground(colot_btw_dark);
            txt.setBackground(colot_btw_dark);
            txt.setForeground(color_white);
            setBtwColor(color_dark);
            setBtwTxtColor(color_white);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void ANSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANSActionPerformed
        txt.setText(txt.getText()+String.valueOf(temp));
    }//GEN-LAST:event_ANSActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanActionPerformed

    }//GEN-LAST:event_tanActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
        apearTxt = txt.getText();
        if(apearTxt.length()==0){
            showMessageDialog(null, "ERORR \nThere are no equations", "Equals cannot be used", ERROR_MESSAGE);
            return;
        }else{
            for(int i =0;i<apearTxt.length();i++){
                System.out.print("here is chare" +Character.toString(apearTxt.charAt(i))+ "\n");
                if(apearTxt.charAt(i)== op){
                    String remaining = apearTxt.substring(i + 1);
                    System.out.print("remaining :"+ remaining);
                    apearTxt=remaining;
                    break;
                }
            }
        }
        num2 = Double.parseDouble(apearTxt);

        switch(op){
            case '+':
            result=num1+num2;
            txt.setText(String.valueOf(result));
            temp = result;//عشان يخزن القيمة في ذرار الانس
            break;
            case '-':
            result=num1-num2;
            txt.setText(String.valueOf(result));
            temp = result;//عشان يخزن القيمة في ذرار الانس
            break;
            case '*':
            result=num1*num2;
            txt.setText(String.valueOf(result));
            temp = result;//عشان يخزن القيمة في ذرار الانس
            break;
            case '/':
            if(num2 ==0){//لو بيقسم علي صفر هيطلع ارور
                showMessageDialog(null, "ERORR \ncan't divided by zero", "divid erorr", ERROR_MESSAGE);
                txt.setText("");
            }else{
                result=num1/num2;
                txt.setText(String.valueOf(result));
                temp = result;//عشان يخزن القيمة في ذرار الانس
            }
            break;
        }
    }//GEN-LAST:event_equalActionPerformed

    private void ACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACActionPerformed
        txt.setText("");
    }//GEN-LAST:event_ACActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
        oper('-');
    }//GEN-LAST:event_minusActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        oper('+');
    }//GEN-LAST:event_plusActionPerformed

    private void dividActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividActionPerformed
        oper('/');
    }//GEN-LAST:event_dividActionPerformed

    private void multActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multActionPerformed
        oper('*');
    }//GEN-LAST:event_multActionPerformed

    private void DELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELActionPerformed
        String all = txt.getText();
        if(all.length()>0){
            all =all.substring(0,all.length()-1);
            txt.setText(all);
        }
    }//GEN-LAST:event_DELActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        set("9");
    }//GEN-LAST:event_nineActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        set("8");
    }//GEN-LAST:event_eightActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        set("7");
    }//GEN-LAST:event_sevenActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        set("6");
    }//GEN-LAST:event_sixActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        set("5");
    }//GEN-LAST:event_fiveActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        set("4");
    }//GEN-LAST:event_fourActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        set("3");
    }//GEN-LAST:event_threeActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        set("2");
    }//GEN-LAST:event_twoActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        set("1");
    }//GEN-LAST:event_oneActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        set("0");
    }//GEN-LAST:event_zeroActionPerformed

    private void dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotActionPerformed
        set(".");
    }//GEN-LAST:event_dotActionPerformed

    private void txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtActionPerformed

    private void txt_sideLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sideLengthActionPerformed
    
    }//GEN-LAST:event_txt_sideLengthActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     SqAreaLaw.setText("");
     squareAreaResult.setText("");
     txt_sideLength.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed
   
    private void txt_sideLengthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sideLengthKeyTyped
        numberOnly(evt);
    }//GEN-LAST:event_txt_sideLengthKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      handleAreaCalculation("square",txt_sideLength.getText(),"",SqAreaLaw,squareAreaResult);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLengthActionPerformed
       
    }//GEN-LAST:event_txtLengthActionPerformed

    private void txtLengthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLengthKeyTyped
        numberOnly(evt);
    }//GEN-LAST:event_txtLengthKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        txtLength.setText("");
        txtWidth.setText("");
        RecAreaResult.setText("");
        RecAreaLaw.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        handleAreaCalculation("rectangle",txtLength.getText(),txtWidth.getText(),RecAreaLaw,RecAreaResult);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtWidthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWidthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWidthActionPerformed

    private void txtWidthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWidthKeyTyped
        numberOnly(evt);
    }//GEN-LAST:event_txtWidthKeyTyped
    
    double num1,num2,result,temp;
    String apearTxt;
    char op;
    boolean change_sign=false; 
    
    
    

    private void oper(char c){
        String apeartxt = txt.getText();
        
        
        
        if(txt.getText().length()>0){
            char lastChar = apeartxt.charAt(apeartxt.length() - 1);
            if (lastChar==op &&c !='-'){
                showMessageDialog(null, "ERORR \ncan't add more than one operation", "Operation erorr", ERROR_MESSAGE);
            }else {
            num1 = Double.parseDouble(txt.getText());
            op=c;
            txt.setText(txt.getText()+String.valueOf(c));
            }
        }else if(txt.getText().length()==0&&c=='-'){
                change_sign=true;
                txt.setText(txt.getText()+'-');
            
        }
    }
    
        
  
    
    /**
     * @param args the command line arguments
     */



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AC;
    private javax.swing.JButton ANS;
    private javax.swing.JPanel AreasWin;
    private javax.swing.JPanel BasicWin;
    private javax.swing.JButton DEL;
    private javax.swing.JPanel ModeWin;
    private javax.swing.JLabel RecAreaLaw;
    private javax.swing.JLabel RecAreaResult;
    private javax.swing.JLabel SqAreaLaw;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton divid;
    private javax.swing.JButton dot;
    private javax.swing.JButton eight;
    private javax.swing.JButton equal;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton minus;
    private javax.swing.JButton mult;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JButton plus;
    private javax.swing.JButton polygon;
    private javax.swing.JButton rectangular;
    private javax.swing.JPanel rectangularWin;
    private javax.swing.JButton rhombus;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JButton square;
    private javax.swing.JLabel squareAreaResult;
    private javax.swing.JPanel squareWin;
    private javax.swing.JButton tan;
    private javax.swing.JButton three;
    private javax.swing.JButton triangle;
    private javax.swing.JButton two;
    private javax.swing.JTextField txt;
    private javax.swing.JTextField txtLength;
    private javax.swing.JTextField txtWidth;
    private javax.swing.JTextField txt_sideLength;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
